// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYwiQQUo4ToipCD77st_PsTZbYwlfgcY',
    appId: '1:227207155336:web:6e8f49a3a0ac4241bd993d',
    messagingSenderId: '227207155336',
    projectId: 'quantom-forge',
    authDomain: 'quantom-forge.firebaseapp.com',
    storageBucket: 'quantom-forge.firebasestorage.app',
    measurementId: 'G-ZEH85WVCTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_QQpqYcZSMgAtr5owEALLHdlqUKG7f7c',
    appId: '1:227207155336:android:5e88f11d1c63967fbd993d',
    messagingSenderId: '227207155336',
    projectId: 'quantom-forge',
    storageBucket: 'quantom-forge.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8c5Q0uEvuHemcLIDuexJjQgn1GdtZbw',
    appId: '1:227207155336:ios:b88e726cf5a37253bd993d',
    messagingSenderId: '227207155336',
    projectId: 'quantom-forge',
    storageBucket: 'quantom-forge.firebasestorage.app',
    iosClientId: '227207155336-ml1iqlsdoatfsdenl49rj48rar78qnbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumForge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8c5Q0uEvuHemcLIDuexJjQgn1GdtZbw',
    appId: '1:227207155336:ios:b88e726cf5a37253bd993d',
    messagingSenderId: '227207155336',
    projectId: 'quantom-forge',
    storageBucket: 'quantom-forge.firebasestorage.app',
    iosClientId: '227207155336-ml1iqlsdoatfsdenl49rj48rar78qnbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumForge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoYwiQQUo4ToipCD77st_PsTZbYwlfgcY',
    appId: '1:227207155336:web:a06476d3c580d33cbd993d',
    messagingSenderId: '227207155336',
    projectId: 'quantom-forge',
    authDomain: 'quantom-forge.firebaseapp.com',
    storageBucket: 'quantom-forge.firebasestorage.app',
    measurementId: 'G-JQBBFV5W5W',
  );
}
