import 'package:flutter/material.dart';
import 'package:quantum_forge/core/utils/xyz_parser.dart';
import 'package:quantum_forge/core/utils/molecule_parser.dart';
import 'package:quantum_forge/core/utils/element_data.dart';
import 'package:quantum_forge/features/reaction_runner/presentation/widgets/interactive_builder_widget.dart';
import 'dart:convert';
import 'dart:typed_data';
import 'package:quantum_forge/core/services/file_picker_service.dart';
import 'package:quantum_forge/core/services/file_picker_models.dart';

class CoordinateEditorScreen extends StatefulWidget {
  const CoordinateEditorScreen({super.key});

  @override
  State<CoordinateEditorScreen> createState() => _CoordinateEditorScreenState();
}

class _CoordinateEditorScreenState extends State<CoordinateEditorScreen> {
  final TextEditingController _controller = TextEditingController();
  List<Atom> _atoms = [];
  
  BuilderTool _currentTool = BuilderTool.navigate;
  String _currentElement = 'C';
  
  @override
  void initState() {
    super.initState();
    // Default example
    final initial = '''3
Water molecule
O  0.00000  0.00000  0.11779
H  0.00000  0.75545 -0.47116
H  0.00000 -0.75545 -0.47116''';
    _controller.text = initial;
    _atoms = MoleculeParser.parse(initial, 'xyz');
    
    _controller.addListener(() {
      // Sync text to viewer if manual typing occurs (debounce in prod)
    });
  }
  
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
  
  void _updateViewer() {
    setState(() {
      _atoms = MoleculeParser.parse(_controller.text, 'xyz'); // Fallback xyz
    });
  }

  void _onAtomsChanged(List<Atom> newAtoms) {
    setState(() {
      _atoms = newAtoms;
      // Reverse sync: generate XYZ from atoms
      final sb = StringBuffer();
      sb.writeln('${newAtoms.length}');
      sb.writeln('Generated by Interactive Builder');
      for (final a in newAtoms) {
        sb.writeln('${a.symbol.padRight(2)} ${a.x.toStringAsFixed(5).padLeft(9)} ${a.y.toStringAsFixed(5).padLeft(9)} ${a.z.toStringAsFixed(5).padLeft(9)}');
      }
      _controller.text = sb.toString();
    });
  }

  Future<void> _importFile() async {
    final picker = FilePickerService();
    final PickedFile? file = await picker.pickStructureFile();

    if (file != null) {
      if (file.bytes != null) {
        final content = utf8.decode(file.bytes!);
        String extension = file.name.split('.').last.toLowerCase();
        final parsedAtoms = MoleculeParser.parse(content, extension);
        
        if (!mounted) return;

        if (parsedAtoms.isNotEmpty) {
          _onAtomsChanged(parsedAtoms);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Successfully loaded ${file.name}')),
          );
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Failed to parse molecule file.')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              const Text(
                '3D Molecular Builder',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.white),
              ),
              const Spacer(),
              FilledButton.icon(
                onPressed: _importFile,
                icon: const Icon(Icons.upload_file),
                label: const Text('Import .mol / .cml'),
                style: FilledButton.styleFrom(
                  backgroundColor: Colors.white24,
                  foregroundColor: Colors.white,
                ),
              ),
              const SizedBox(width: 12),
              FilledButton.icon(
                onPressed: () {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('AI TS Guesser (LST) generating saddle point...')),
                  );
                  Future.delayed(const Duration(seconds: 1), () {
                    final tsGuess = '''3
TS Guess (LST interpolation)
O  0.00000  0.00000  0.20000
H  0.00000  0.90000 -0.50000
H  0.00000 -0.90000 -0.50000''';
                    _onAtomsChanged(MoleculeParser.parse(tsGuess, 'xyz'));
                  });
                },
                icon: const Icon(Icons.auto_awesome),
                label: const Text('AI TS Guesser'),
                style: FilledButton.styleFrom(
                  backgroundColor: Colors.purpleAccent,
                  foregroundColor: Colors.white,
                ),
              ),
              const SizedBox(width: 12),
              FilledButton.icon(
                onPressed: _updateViewer,
                icon: const Icon(Icons.refresh),
                label: const Text('Sync Text'),
                style: FilledButton.styleFrom(
                  backgroundColor: const Color(0xFF4FC3F7),
                  foregroundColor: Colors.black,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          // Toolbox
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.05),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
            ),
            child: Row(
              children: [
                _buildToolBtn(BuilderTool.navigate, Icons.pan_tool, 'Navigate'),
                _buildToolBtn(BuilderTool.draw, Icons.edit, 'Draw'),
                _buildToolBtn(BuilderTool.delete, Icons.delete, 'Delete'),
                const SizedBox(width: 20),
                const Text('Element:', style: TextStyle(color: Colors.white70)),
                const SizedBox(width: 8),
                DropdownButton<String>(
                  value: _currentElement,
                  dropdownColor: const Color(0xFF203A43),
                  style: const TextStyle(color: Colors.white),
                  underline: const SizedBox(),
                  onChanged: (String? newValue) {
                    if (newValue != null) {
                      setState(() => _currentElement = newValue);
                    }
                  },
                  items: ElementData.colors.keys
                      .map<DropdownMenuItem<String>>((String value) {
                    return DropdownMenuItem<String>(
                      value: value,
                      child: Text(value, style: const TextStyle(fontWeight: FontWeight.bold)),
                    );
                  }).toList(),
                ),
                const Spacer(),
                const Text('Draw Mode: Click to add, drag to bond', style: TextStyle(color: Colors.white38, fontSize: 12)),
              ],
            ),
          ),
          const SizedBox(height: 16),
          Expanded(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Text Editor
                Expanded(
                  flex: 2,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.black.withValues(alpha: 0.3),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
                    ),
                    padding: const EdgeInsets.all(16),
                    child: TextField(
                      controller: _controller,
                      maxLines: null,
                      expands: true,
                      style: const TextStyle(
                        fontFamily: 'Consolas',
                        color: Colors.greenAccent,
                        fontSize: 14,
                      ),
                      decoration: const InputDecoration(
                        border: InputBorder.none,
                        hintText: 'Paste .xyz coordinates here...',
                        hintStyle: TextStyle(color: Colors.white24),
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 24),
                // 3D Builder
                Expanded(
                  flex: 3,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.black.withValues(alpha: 0.15),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(12),
                      child: InteractiveBuilderWidget(
                        initialAtoms: _atoms,
                        currentTool: _currentTool,
                        currentElement: _currentElement,
                        onAtomsChanged: _onAtomsChanged,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildToolBtn(BuilderTool tool, IconData icon, String label) {
    final isActive = _currentTool == tool;
    return Padding(
      padding: const EdgeInsets.only(right: 8.0),
      child: TextButton.icon(
        style: TextButton.styleFrom(
          backgroundColor: isActive ? const Color(0xFF4FC3F7).withValues(alpha: 0.2) : Colors.transparent,
          foregroundColor: isActive ? const Color(0xFF4FC3F7) : Colors.white54,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
        ),
        onPressed: () => setState(() => _currentTool = tool),
        icon: Icon(icon, size: 18),
        label: Text(label),
      ),
    );
  }
}
