import 'dart:convert';
import 'package:quantum_forge/core/services/web_services.dart';

/// Resolves chemical names and SMILES strings to 3D XYZ structures.
///
/// Strategy:
///   Autocomplete → PubChem autocomplete endpoint (live-as-you-type suggestions)
///   Resolution   → PubChem 3D SDF → convert to XYZ  (primary, ~115M compounds)
///               → NCI Cactus XYZ                    (fallback, ~5M compounds)
class ChemicalResolverService {
  String _lastSource = '';
  String get lastSource => _lastSource;

  // ── Autocomplete ────────────────────────────────────────────────────────────
  /// Returns up to [limit] name suggestions for a partial query.
  /// Uses PubChem's autocomplete endpoint — extremely fast, no 3D fetch.
  Future<List<String>> getSuggestions(String partial, {int limit = 8}) async {
    final q = partial.trim();
    if (q.length < 2) return [];

    // SMILES strings contain these chars — skip autocomplete, go straight to resolve
    if (_looksLikeSmiles(q)) return [];

    try {
      final uri = 'https://pubchem.ncbi.nlm.nih.gov/rest/autocomplete/compound/${Uri.encodeComponent(q)}/json?limit=$limit';
      final responseBody = await WebServices.fetchString(uri);

      final data = jsonDecode(responseBody) as Map<String, dynamic>;
      final total = data['total'] as int? ?? 0;
      if (total == 0) return [];

      final dict = data['dictionary_terms'] as Map<String, dynamic>?;
      final compounds = dict?['compound'] as List<dynamic>?;
      if (compounds == null) return [];

      return compounds.cast<String>().take(limit).toList();
    } catch (_) {
      return [];
    }
  }

  // ── XYZ Resolution ──────────────────────────────────────────────────────────
  /// Resolves a chemical name or SMILES to an XYZ string.
  /// Primary: PubChem 3D SDF  → parsed to XYZ
  /// Fallback: NCI Cactus direct XYZ
  Future<String?> resolveToXyz(String query) async {
    final q = query.trim();
    if (q.isEmpty) return null;

    // 1. Try PubChem 3D SDF
    final pubchemXyz = await _resolveViaPubChem(q);
    if (pubchemXyz != null) {
      _lastSource = 'PubChem';
      return pubchemXyz;
    }

    // 2. Fallback: NCI Cactus
    final cactusXyz = await _resolveViaCactus(q);
    if (cactusXyz != null) {
      _lastSource = 'Cactus';
      return cactusXyz;
    }

    return null;
  }

  // ── PubChem SDF → XYZ ──────────────────────────────────────────────────────
  Future<String?> _resolveViaPubChem(String query) async {
    try {
      // Decide lookup route: SMILES → 'smiles', name → 'name'
      final route = _looksLikeSmiles(query) ? 'smiles' : 'name';
      final uri = 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/$route/${Uri.encodeComponent(query)}/record/SDF/?record_type=3d';
      final responseBody = await WebServices.fetchString(uri);
      if (responseBody.trim().isEmpty) return null;

      return _sdfToXyz(responseBody);
    } catch (_) {
      return null;
    }
  }

  // ── NCI Cactus ─────────────────────────────────────────────────────────────
  Future<String?> _resolveViaCactus(String query) async {
    try {
      final uri = 'https://cactus.nci.nih.gov/chemical/structure/${Uri.encodeComponent(query.trim())}/file?format=xyz';
      final responseBody = await WebServices.fetchString(uri);
      if (responseBody.trim().isNotEmpty) {
        return responseBody;
      }
    } catch (_) {}
    return null;
  }

  // ── SDF → XYZ converter ────────────────────────────────────────────────────
  /// Parses PubChem's V2000 SDF atom block into a minimal XYZ string.
  String? _sdfToXyz(String sdf) {
    try {
      final lines = sdf.split('\n');
      // The counts line is line index 3 (0-based)
      if (lines.length < 4) return null;
      final countLine = lines[3];
      final atomCount = int.tryParse(countLine.substring(0, 3).trim());
      if (atomCount == null || atomCount == 0) return null;

      final atomLines = lines.skip(4).take(atomCount).toList();
      final sb = StringBuffer();
      sb.writeln(atomCount);
      sb.writeln('Generated by PubChem 3D');

      for (final line in atomLines) {
        if (line.length < 34) continue;
        final x = double.tryParse(line.substring(0, 10).trim());
        final y = double.tryParse(line.substring(10, 20).trim());
        final z = double.tryParse(line.substring(20, 30).trim());
        final sym = line.substring(31, 34).trim();
        if (x == null || y == null || z == null || sym.isEmpty) continue;
        sb.writeln(
          '${sym.padRight(2)} '
          '${x.toStringAsFixed(4).padLeft(10)} '
          '${y.toStringAsFixed(4).padLeft(10)} '
          '${z.toStringAsFixed(4).padLeft(10)}',
        );
      }
      return sb.toString();
    } catch (_) {
      return null;
    }
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────
  bool _looksLikeSmiles(String q) =>
      q.contains('=') ||
      q.contains('#') ||
      q.contains('(') ||
      q.contains(')') ||
      q.contains('[') ||
      q.contains(']') ||
      q.contains('@') ||
      q.contains('/') ||
      q.contains('\\');
}
